name: postage_stamp_maker
description: Let's make some postage stamps!
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_downloader_web: ^2.0.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.1.2
  screenshot: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
